apiVersion: v1
kind: Pod
metadata:
  labels:
    component: etcd
  name: px-etcd
  namespace: kube-system
spec:
  nodeName: node03
  containers:
  - command:
    - etcd
    - --advertise-client-urls=http://<node03_ip>:2379
    - --data-dir=/var/lib/etcd
    - --initial-advertise-peer-urls=http://<node03_ip>:2380
    - --initial-cluster=node03=http://<node03_ip>:2380
    - --listen-client-urls=http://0.0.0.0:2379
    - --listen-peer-urls=http://0.0.0.0:2380
    - --name=node03
    image: k8s.gcr.io/etcd:3.3.10
    imagePullPolicy: IfNotPresent
    name: etcd
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd-data
  hostNetwork: true
  volumes:
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data
