apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "redis"
spec:
  template:
    metadata:
      labels:
        app: redis
        name: "redis"
    spec:
      containers:
        - name: redis
          image: "redis:5-alpine"
          command:
            - "redis-server"
          args:
            - "--protected-mode"
            - "no"
            - "--appendonly"
            - "yes"
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
          ports:
            - name: redis
              containerPort: 6379
              protocol: "TCP"
            - name: cluster
              containerPort: 16379
              protocol: "TCP"
          volumeMounts:
            - name: "redis-conf"
              mountPath: "/etc/redis"
            - name: "redis-data"
              mountPath: "/data"
      volumes:
        - name: "redis-data"
          persistentVolumeClaim:
             claimName: px-redis-data
        - name: "redis-conf"
          persistentVolumeClaim:
             claimName: px-redis-conf
